# Hand-curated descriptions for every (file, column) pair this pipeline emits.
# Edit this file when you add/rename a panel column. `build_data_dictionary()`
# joins these against the actual output schemas and fails if anything drifts
# (missing description for a real column, or curated entry for a column that
# no longer exists).
#
# Schema fields:
#   description     \u2014 what the value means, plain English
#   form_source     \u2014 IRS Form 990 line(s) where applicable, or pipeline derivation
#   coverage        \u2014 year range as observed in the output
#   coverage_notes  \u2014 known limitations / gaps; surfaces in dashboard tooltips

# Shared dimension columns appear in every panel. Defined once, expanded per
# panel by build_data_dictionary().
.DD_SHARED_DIMS <- tibble::tribble(
  ~column,             ~description,                                              ~form_source,                                        ~coverage_notes,
  "Organization Type", "501(c) classification (e.g. '501(c)(3) Public Charities', '501(c)(4)'). Public charities and private foundations are split out within (c)(3).", "BMF subsection code mapped via derive_organization_type().",     "",
  "Subsector",         "NCCS major group (NTEE Level-1) \u2014 26 categories like 'ART', 'EDU', 'HEL'.", "BMF NTEE-V2 code mapped via derive_subsector().",  "",
  "Size",              "Static per-EIN size band 1-6 by total_expenses, or 0 if no CORE filing ever observed. Locked per EIN \u2014 does not float year-to-year.", "Derived from most-recent non-NA total_expenses across CORE 990 + 990-PF.", "Size=0 means the org has BMF metadata but no CORE filing on record.",
  "Census Region",     "US Census-defined region (Northeast / Midwest / South / West).",          "Derived from Census State via derive_census_region().",                "",
  "Census State",      "2-letter USPS state code from BMF geocode.",                              "BMF CENSUS_STATE_ABBR.",                                                "~8% of BMF rows have NA Census State \u2014 pass-through documented upstream gap.",
  "Census County",     "Canonical Census county name (NAMELSAD), de-duplicated against the county FIPS crosswalk so 'Wayne' and 'Wayne County' collapse to one county.", "nccs-data-bmf county FIPS crosswalk, keyed on (state, raw label); Connecticut resolved to its 2022 planning regions by coordinate via the CT planning-region crosswalk (rounded geo_lat/geo_lon).", "NA = unassigned: the geocoded label was ambiguous or unresolved (bare 'Baltimore'/'St. Louis', cross-state mislabels) and could not be mapped to one county. Connecticut is the exception \u2014 its planning-region labels are resolved by coordinate, not left unassigned. ~8% of rows also have NA state upstream.",
  "County FIPS",       "5-character county GEOID (2-char state FIPS + 3-char county FIPS, leading zeros preserved). Stable, collision-proof key \u2014 prefer over the name (Baltimore city 24510 vs Baltimore County 24005).", "nccs-data-bmf county FIPS crosswalk (Census TIGER GEOID).", "NA wherever Census County is NA (unassigned).",
  "Metro/Micro Area",  "OMB-defined CBSA name (Metropolitan or Micropolitan Statistical Area).",  "nccs-data-bmf cbsa_crosswalk, joined on County FIPS (OMB 2023).", "NA for rural counties (no CBSA) and for unassigned counties \u2014 distinguish via County FIPS / resolution.",
  "CBSA Code",         "OMB CBSA code for the Metro/Micro Area. Stable key for metro rollups.",   "nccs-data-bmf cbsa_crosswalk, joined on County FIPS (OMB 2023).", "NA for rural / unassigned counties."
)

# Per-panel non-dimension columns.
.DD_PANEL_COLS <- tibble::tribble(
  ~file,                       ~column,               ~description,                                                                         ~form_source,                                                                                         ~coverage_notes,
  # number_nonprofits
  "number_nonprofits.parquet", "Year",                "Tax year of the count.",                                                              "BMF active-window: org counted in year Y if org_year_first \u2264 Y \u2264 org_year_last.",                  "",
  "number_nonprofits.parquet", "Number of Nonprofits","Count of distinct EINs active in this (Year, dim) cell per the BMF active-window rule.", "Aggregate of BMF rows.",                                                                            "Excludes orgs without a BMF window. 1989\u20132026 range.",
  # finances
  "finances.parquet",          "Year",                "Tax year as reported on the filing.",                                                 "CORE filing tax_year.",                                                                              "",
  "finances.parquet",          "Total Revenues",      "Sum of total revenue across orgs in the (Year, dim) cell.",                          "990: Form 990 Pt VIII Line 12 (total revenue). 990-PF: Pt I Line 12 Col (a). 990EZ: total_revenue.",  "",
  "finances.parquet",          "Total Expenses",      "Sum of total expenses across orgs in the (Year, dim) cell.",                         "990: Form 990 Pt IX Line 25 Col A (total functional expenses, harmonized to total_expenses). 990-PF: Pt I Line 26 Col (a). 990EZ: total_expenses.", "",
  "finances.parquet",          "Total Assets",        "Sum of end-of-year total assets across orgs.",                                       "990: Pt X Line 16 EOY (total_assets_eoy). 990-PF: Pt II Line 16 Col (b). 990EZ: total_assets_eoy.",   "",
  "finances.parquet",          "Total Benefits",      "Sum of total personnel costs (compensation + salaries/wages + pension + other employee benefits) across orgs. NOT including Pt IX-4 'Benefits paid to or for members' \u2014 that is a different concept (member payouts, not employee comp).", "Form 990 Pt IX Lines 5+6+7+8+9.  990-PF and 990EZ do not carry these lines \u2014 those filers contribute NA.", "1989\u20132011: partial 2-line proxy (lines 5+7 only); lines 6/8/9 not extracted in legacy data. Visible discontinuity at 2012 as full 5-line sum becomes available.",
  # pf_grants
  "pf_grants.parquet",         "Year",                "Tax year as reported on the 990-PF filing.",                                          "CORE 990-PF tax_year.",                                                                              "",
  "pf_grants.parquet",         "Total Contributions", "Sum of contributions paid OUT by private foundations (grants given to grantees) in the cell.", "Form 990-PF Pt I Line 25 Col (a): contributions_paid.",                                       "2011\u20132016: ~50% underreported vs prior dashboard. IRS never released the 2017\u20132019 backfill that populated PZ-HRMN for those years; processed_merged 990pf has the thinner coverage.",
  # government_grants
  "government_grants.parquet", "Year",                "Tax year as reported on the 990 filing.",                                             "efile Phase 0 government_grants.tax_year.",                                                          "",
  "government_grants.parquet", "Total Government Grants", "Sum of government grants/contributions RECEIVED by 501(c) orgs in the (Year, dim) cell. This is income received from government sources \u2014 NOT Schedule I grants paid out to governments.", "Form 990 Part VIII line 1e, via efile Phase 0 (source_xpath /Return/ReturnData/IRS990/GovernmentGrantsAmt; NODC F9_08_REV_CONTR_GOVT_GRANT).", "990 filers only (990-PF/990-EZ do not carry line 1e). Coverage 2021\u20132024 in e-file; this panel publishes 2021\u20132023 (2024 filings still arriving). Most filers report none, so many cells are NA.",
  # program_related_investments
  "program_related_investments.parquet", "Year",      "Tax year as reported on the 990-PF filing.",                                          "efile Phase 0 program_related_investments.tax_year.",                                               "",
  "program_related_investments.parquet", "Total Program-Related Investments", "Sum of private-foundation program-related investments (PRI) totals across orgs in the (Year, dim) cell.", "Form 990-PF Part IX-B aggregate total (renumbered Part VIII-B for TY2021+), via efile Phase 0 (source_xpath /Return/ReturnData/IRS990PF/SumOfProgramRelatedInvstGrp/TotalAmt; NODC PF_09_PROG_RLTD_INVEST_AMT_TOT).", "990-PF filers only. Coverage 2021\u20132024 in e-file; this panel publishes 2021\u20132023 (2024 filings still arriving). Most foundations report no PRI, so many cells are NA.",
  # daf
  "daf.parquet",               "Year",                "Tax year as reported on the Schedule D filing.",                                      "DAF e-file Schedule D, harmonized.",                                                                 "",
  "daf.parquet",               "Number of Nonprofits","BMF active-window count of orgs in the cell \u2014 denominator for the dashboard's 'Percentage of Nonprofits with DAFs' metric.", "Aggregate of BMF rows where org_year_first \u2264 Year \u2264 org_year_last.",                  "Matches the number_nonprofits panel for the same cells.",
  "daf.parquet",               "Number of DAFs",      "Sum of donor-advised funds (and 'other similar funds') reported end-of-year, across orgs in the cell.", "Form 990 Schedule D Part I Line 1: SD_01_TOT_NUM_EOY_DAF + SD_01_TOT_NUM_EOY_OTH.",        "DAF reporting began 2008; coverage in this dataset starts 2021 (earlier years not in e-file).",
  "daf.parquet",               "Total Contributions", "Sum of aggregate contributions to DAFs (and OSFs) for the cell.",                    "Schedule D Pt I Line 2: SD_01_AGGREGATE_CONTR_DAF + _OTH.",                                          "",
  "daf.parquet",               "Total Grants",        "Sum of aggregate grants made from DAFs (and OSFs).",                                 "Schedule D Pt I Line 3: SD_01_AGGREGATE_GRANT_DAF + _OTH.",                                          "",
  "daf.parquet",               "Total Value",         "Sum of aggregate end-of-year value of DAFs (and OSFs).",                             "Schedule D Pt I Line 4: SD_01_AGGREGATE_VALUE_EOY_DAF + _OTH.",                                      "",
  "daf.parquet",               "Has DAF",             "Count of orgs in the cell with at least one DAF (num_dafs > 0).",                    "Derived per-row from Number of DAFs > 0, summed.",                                                   "",
  # nested_geographies
  "nested_geographies.csv",    "Census State",        "2-letter USPS state code.",                                                          "BMF.",                                                                                               "",
  "nested_geographies.csv",    "Census County",       "Canonical Census county name. Data-derived allowlist of selectable counties.",        "nccs-data-bmf county FIPS crosswalk.",                                                               "Unassigned (NA-county) rows are dropped from this lookup.",
  "nested_geographies.csv",    "County FIPS",         "5-character county GEOID (leading zeros preserved). Stable county key.",               "nccs-data-bmf county FIPS crosswalk.",                                                               "",
  "nested_geographies.csv",    "Metro/Micro Area",    "OMB CBSA name.",                                                                      "nccs-data-bmf cbsa_crosswalk (joined on County FIPS).",                                              "NA for rural counties.",
  "nested_geographies.csv",    "CBSA Code",           "OMB CBSA code for the Metro/Micro Area.",                                              "nccs-data-bmf cbsa_crosswalk (joined on County FIPS).",                                              "NA for rural counties.",
  "nested_geographies.csv",    "Census Region",       "US Census region.",                                                                  "Derived from state.",                                                                                "",
  # county_fips_crosswalk
  "county_fips_crosswalk.parquet", "Census State",    "2-letter USPS state code.",                                                          "nccs-data-bmf county FIPS crosswalk.",                                                               "",
  "county_fips_crosswalk.parquet", "County (raw)",    "Raw free-text county label as emitted by the geocoder, before canonicalization. Audit trail for every label and its fate.", "nccs-data-bmf county FIPS crosswalk (geo_county_raw).",                                  "",
  "county_fips_crosswalk.parquet", "Census County",   "Canonical Census county name (NAMELSAD: County / Parish / Borough / Census Area / Municipality / independent city / Municipio).", "nccs-data-bmf county FIPS crosswalk (resolved from geocoded lat/lon via Census TIGER).", "NA when Resolution is not 'resolved'.",
  "county_fips_crosswalk.parquet", "County FIPS",     "5-character county GEOID (2-char state FIPS + 3-char county FIPS, leading zeros preserved). Stable key for county-level filtering \u2014 use this rather than the name, which collides across states.", "nccs-data-bmf county FIPS crosswalk (Census TIGER GEOID).", "NA when Resolution is not 'resolved'.",
  "county_fips_crosswalk.parquet", "Resolution",      "Upstream verdict on mapping the raw label to one Census county: 'resolved' (one match, has FIPS), 'ambiguous' (could be >1 county, e.g. bare Baltimore / CT planning regions; NA FIPS), 'unresolved' (cross-state mislabel; NA FIPS).", "nccs-data-bmf county FIPS crosswalk.", "Explains every NA FIPS \u2014 lets consumers tell mapping failure from rural. This is the LABEL-grain audit artifact: CT planning-region labels stay 'ambiguous' here, but the panels resolve CT by coordinate (CT planning-region crosswalk), so CT is NOT unassigned in the panel data.",
  # cbsa_crosswalk (DATA-DERIVED universe \u2014 see caveat below)
  "cbsa_crosswalk.parquet",    "County FIPS",         "5-character county GEOID (leading zeros preserved). Join key to the county dimension.", "nccs-data-bmf cbsa_crosswalk.",                                                                  "",
  "cbsa_crosswalk.parquet",    "CBSA Code",           "OMB CBSA code.",                                                                       "nccs-data-bmf cbsa_crosswalk (OMB 2023 delineation).",                                              "",
  "cbsa_crosswalk.parquet",    "Metro/Micro Area",    "OMB CBSA title (Metropolitan or Micropolitan Statistical Area name).",                  "nccs-data-bmf cbsa_crosswalk (OMB 2023 delineation).",                                              "",
  "cbsa_crosswalk.parquet",    "CBSA Type",           "'Metropolitan Statistical Area' or 'Micropolitan Statistical Area'.",                   "nccs-data-bmf cbsa_crosswalk (OMB 2023 delineation).",                                              "",
  "cbsa_crosswalk.parquet",    "Central/Outlying",    "Whether the county is 'Central' or 'Outlying' within its CBSA.",                         "nccs-data-bmf cbsa_crosswalk (OMB 2023 delineation).",                                              "",
  "cbsa_crosswalk.parquet",    "CSA Code",            "OMB Combined Statistical Area code, for rolling CBSAs up to CSAs.",                     "nccs-data-bmf cbsa_crosswalk (OMB 2023 delineation).",                                              "NA when the CBSA is not part of any CSA.",
  "cbsa_crosswalk.parquet",    "CSA Title",           "OMB Combined Statistical Area name.",                                                   "nccs-data-bmf cbsa_crosswalk (OMB 2023 delineation).",                                              "NA when the CBSA is not part of any CSA.",
  "cbsa_crosswalk.parquet",    "Delineation Year",    "OMB delineation vintage (2023).",                                                       "nccs-data-bmf cbsa_crosswalk.",                                                                     "DATA-DERIVED universe: only resolved counties present in our geocoded data, left-joined to OMB. NOT the full OMB county/CBSA universe; do not use as a complete dropdown allowlist."
)
